package com.openjob.common.enums;

public enum MailCase {
    MAIL_COMPANY_CREATED,
    MAIL_JOB_HAS_MATCH,
    MAIL_JOB_REJECTED,
    MAIL_JOB_APPROVED,
    MAIL_JOB_STOP_TO_USER,
    MAIL_JOB_REOPEN_TO_USER,
    MAIL_USER_DEACTIVATED,
    MAIL_USER_REACTIVATED,
    MAIL_COMPANY_DEACTIVATED,
    MAIL_COMPANY_REACTIVATED,
    MAIL_JOB_DEACTIVATED,
    MAIL_JOB_REACTIVATED,
    MAIL_JOB_EXPIRED,
    MAIL_JOB_HAS_APPLICATION
}
